### ISSUE TITLE
来修bug了

### ISSUE THREAD

**Issue by CaledoniaProject** [zema1/watchvuln#28]
```
[INFO] 2023/04/07 22:18 [oscs]: parsing page 1
[INFO] 2023/04/07 22:18 [oscs]: page 1 contains 10 vulns
panic: runtime error: integer divide by zero

goroutine 186503 [running]:
github.com/zema1/watchvuln/grab.(*TiCrawler).GetPageCount(0xc0002f7900, {0x11051d8?, 0xc000378000}, 0xa)
        github.com/zema1/watchvuln/grab/ti.go:53 +0x3be
main.collectUpdate.func1()                                                                                                                                                              github.com/zema1/watchvuln/main.go:394 +0xa4
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by zema1** [comment]
来了来了，大伙别催了，今天就休 ✋

**Comment by zema1** [comment]
已修复，更新后如果还有问题可以新开 issue https://github.com/zema1/watchvuln/releases/tag/v0.7.0

**Comment by CaledoniaProject** [comment]
docker镜像更新了吗？
